### PR TITLE
Adding SipHash, and the proposed N3980.

### PR DESCRIPTION
**Pull request by vtnerd**
The N3980 differs the proposed in that it a serialize method will work with
both hashing, Cereal, and boost::serialization.

### CODE REVIEW

**Comment by vtnerd** [comment]
@Fraser999 are the traits too much? I thought it made it easier since containers all used thet same code, but following the traits code is a bit of a pain too.

**Comment by ned14** [comment]
Lee, std::random_device on Windows directly uses RtlGenRandom from the kernel. On Linux, recent libstdc++'s use /dev/urandom, on BSD /dev/random, both of which are PRNGs which are inexhaustible. I am told earlier libstdc++'s used to read 256 bits from /dev/random and used those to seed an internal SHA256 from which randomness came, or if the CPU supported RDRAND it used that directly.

My point is you don't need a Mersenne Twister in there. Also, the twister is fast on Intel, but horribly slow on ARM. He also has enormous startup costs and is very poor suited for small quantities of randomness.

**Comment by ned14** [comment]
Oh before I forget make very sure you test the output is not all zeros. Some version of libstdc++ on ARM did that to me, it only by lucky chance raised a separate bug which provoked a bit of head scratching because I assumed it just worked. It's a bit like hardware_concurrency() being zero, it's allowed by the standard but you tend to code assuming >= 1.

**Comment by ned14** [comment]
Regarding valgrind suppressions, it's often much better to encode the suppressions into the source code itself rather than rely on external suppression files. See http://valgrind.org/docs/manual/manual-core-adv.html.

**Comment by vtnerd** [comment]
The latest version is using a system-wide thread-local `CryptoPP::RandomNumberGenerator` object. I looked at the source, that object uses /dev/random and then generates random numbers using AES and X.917 guidelines. Specifically the Cryptopp documentation states:
> RNG from ANSI X9.17 Appendix C, seeded using an OS provided RNG.

I went with Cryptopp because it wasn't subject to differences in std::random_device implementations, which doesn't seem to enforce good RNG practices. Unfortunately, the Cryptopp random number generator also intentionally doesn't initialize some variables, which is what causs the valgrind complaints. Didn't look to be an issue, but it was the openssl method of sketchily using previous contents as additional "entropy".

As for the valgrind stuff, I posted earlier in this chain that I was considering using the function calls. I didn't do it for some reason (didn't state why I opposed it) - I think you had to link to the valgrind library. I look into it again.

**Comment by ned14** [comment]
A major advantage of OS provided crypto randomness is that it can be patched with fixes without needing a rebuild of all your software. For that alone, that's why I choose it. AFIO gained crypto support recently, and it's a mutex protected random_device as from examination of the various STLs I decided that recent STLs are well implemented, plus they are much faster for say 4 bytes of randomness as compared to an AES source which has no choice but to produce a minimum of 16 bytes for AES128. I suppose you could, like random_device, keep a buffer to amortise that.

No external library is needed for valgrind annotation. In fact the macros compile into __asm bytecodes directly, so there isn't even code in there. You can safely leave the valgrind instrumentation inside production release executables, indeed performance isn't affected either.

**Comment by vtnerd** [comment]
> A major advantage of OS provided crypto randomness is that it can be patched with fixes without needing a rebuild of all your software.

This is only required because we do a static-link against Cryptopp and have the source in the project. Otherwise, a patch to Cryptopp's random number generation wouldn't neccessarily require a rebuild. The C++ lib is MUCH less likely to do a breaking ABI change, so it does have that benefit.

My problem is the weak language used to define std::random_device; it is not defined to be cryptographically secure (which I know is an abstract concept that can't be defined adequately, but they could've still required `if (entropy() == 0) throw;`!). We basically have to inspect/test each platform to ensure its actually generating cryptographically secure numbers. I guess it could be argued that we should be doing that anyway, however verifying good random number generation is difficult. Using Cryptopp seemed like the safe approach (assuming it did the correct thing for all supported platforms), since its specifically designed for cryptographic usage.

> No external library is needed for valgrind annotation.

I remember what my issue was with the valgrind functions. From the docs:
> You are encouraged to copy the valgrind/*.h headers into your project's include directory, so your program doesn't have a compile-time dependency on Valgrind being installed. The Valgrind headers, unlike most of the rest of the code, are under a BSD-style license so you may include them without worrying about license incompatibility.

I saw that a valgrind header was needed for compilation. I didn't think about copying the header into the library - which I guess works. Since I don't want to make valgrind a required dependency, is it worth adding the header? In this pull request, or make another (with new JIRA ticket)? No one is currently using this code anyway, so the valgrind errors on appear when running the related unittests (it does not "infect" other parts of code yet).

**Comment by vtnerd** [comment]
I forgot to mention, I'm actually using `maidsafe/common/crypto.h` which returns a base class into cryptopp. The CPP usage the AES implementation, but it can be changed out. Were you going to push for std::random_device there too? Technically we could write our own implementation of a cryptopp RNG that uses std::random_device without changing the rest of the code.

**Comment by ned14** [comment]
Note that random_device::entropy() isn't useful - it must return zero if the source is a pseudo random generator even if that generation is as good as random. Regarding inspecting each STL implementation to see if it's sane, one could count my review of the implementations above as being exactly that. The standard's wording is indeed loose, but we don't care if the versions of Dinkumware, libstdc++ and libc++ we use are crypto safe (and they are).

Regarding including the valgrind headers, yeah I've been doing that for years in my own code now. The headers even compile under MSVC safely. You genuinely can turn them on as a way of documenting the code's peculiarities and forget about them.

Regarding replacing cryptopp where possible, I'd personally be in favour of always the kernel for randomness only. Unlike crypto where an implementation can be proved to meet a specification and therefore critical defects are per-algorithm rather than per-implementation, it's the other way round for randomness generation. As much as kernel based randomness when subverted subverts the entire system e.g. the American's very clever root kit for hard drive firmwares, equally fixes are system wide too.

**Comment by vtnerd** [comment]
I definitely agree with your argument for OS RNG (I _really_ like BSD's arc4random function), because I'm not sure that Cryptopp handles forks correctly (it MUST reseed). However, std::random_device isn't defined to call any OS utilities, and can pretty much do what it wants. For example (from cppreference.com):
> The implementations in libc++ and libstdc++ expect token to be the name of a character device that produces random numbers when read from, with the default value "/dev/urandom", although where the CPU command RDRND is available, libstdc++ uses that as the default. 

Since the actual entropy gathering implementation of hardware cannot verified, many people (including me) don't like the hardware being the only source of randomness. Theodore Ts'o of Linux fame refused to make RDRND the only source of entropy in the Linux kernel. Luckily specifying "/dev/urandom" to std::random_device will disable this mode. However, libstdc++ doesn't check the return code from the read! Looks like I'll be finding their bugzilla shortly.

Is your issue that SipHash uses Cryptopp, or do you want to see all cryptographic keys generated via OS functions? Because this discussion seems to be bigger than just this patch, and thus better for the dev mailing list. If the issue is one of performance specific to SipHash + unordered_map usage, I can measure the differences. Although I'd prefer to keep it consistent with how the rest of the project generates cryptographically secure numbers (original SipHash paper said to seed with CSRNG).

**Comment by ned14** [comment]
Yep, you're right about libstdc++ being defective here. My memory must be failing! It firstly defaults to RDRAND on Intel, and it secondly fails to check if fread() fails.

After you submit the bug, email me the link and I'll make sure Jonathan is CCied into it which should speed its fix. I also personally think there is a strong case for a "hardware" source which is not the default. The default should be /dev/urandom on POSIX, as it is in libc++.

Personally speaking I'd prefer all crypto secure randomness to come from the kernel. The code required is very straightforward, I can even supply you a snippet from my archives on request.

**Comment by vtnerd** [comment]
> After you submit the bug, email me the link and I'll make sure Jonathan is CCied into it which should speed its fix.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65142

>  I also personally think there is a strong case for a "hardware" source which is not the default. The default should be /dev/urandom on POSIX, as it is in libc++.

Agreed, letting the OS handle mixing various forms of entropy (including hardware) seems like the right approach. I think this may be a harder sell to the gcc team.

**Pull request merged**
